_wandb:
    value:
        cli_version: 0.23.1
        e:
            lxn4tqe9xd20bmmc72ddnjl12a6cpbdc:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "5368709120"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "155535577088"
                email: lee137ritsss@gmail.com
                executable: /Users/wadarei/2WINS_AI_test/.venv/bin/python
                git:
                    commit: caa75080b07cb07b5b68623cbaaa70896891c28d
                    remote: https://github.com/ReiWada1216/2WINS_AI_test
                host: wadareinoMacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/wadarei/2WINS_AI_test/main.py
                python: CPython 3.13.3
                root: /Users/wadarei/2WINS_AI_test
                startedAt: "2025-12-06T09:08:07.405837Z"
                writerId: lxn4tqe9xd20bmmc72ddnjl12a6cpbdc
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 16
            "4": 3.13.3
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 16
class_weights:
    value:
        - 1
        - 2.86
device:
    value: mps
epochs:
    value: 20
learning_rate:
    value: 0.001
original_size:
    value: 1024
patch_size:
    value: 256
seed:
    value: 42
